name: SimpleVoid
main: dev.rob2.simplevoid.SimpleVoid
version: 1.0.0
api-version: 1.20
commands:
  simplevoid:
    description: Create a void world
    usage: /simplevoid <worldname>
    permission: simplevoid.create
permissions:
  simplevoid.create:
    default: op
